name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ou master, dependendo do nome da sua branch principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou a versão do Node.js que você está usando

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false # Para evitar que warnings sejam tratados como erros

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # pasta que será deployada
          branch: gh-pages # branch onde será feito o deploy